# Generated by Django 3.2.20 on 2023-08-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.CharField(max_length=800, verbose_name='Description')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('author', models.CharField(blank=True, max_length=254, null=True, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=800, verbose_name='Comment')),
                ('author', models.CharField(blank=True, max_length=254, null=True, verbose_name='Author')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post', verbose_name='Post')),
            ],
        ),
    ]
