# Generated by Django 3.2.20 on 2023-09-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=254, null=True, verbose_name='Author')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post', verbose_name='Post')),
            ],
        ),
    ]
